services:
  babel:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./leveldb:/app/leveldb"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 3
      start_period: 30s
      timeout: 1s
    restart: always
