services:
  babel:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 3
      start_period: 30s
      timeout: 1s
    restart: always
  redis:
    image: "redis:7"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "./data:/data"
    restart: always
